(EZ-48) Add support for debian systemd
This commit updates both the PE and foss build pipelines to correctly
install systemd scripts for packages built with EZBake. It also cleans
up some of the logic in the {pre,post}{inst,rm} debian scripts.

This only upgrades Ububtu Xenial to systemd, even though it really
should include Debian Jessie. We disable the service in the prerm, which
prevents us from recording and preserving the state of the service on
upgrade. This is addressed in this change, so it should be more easily
fixed for future upgrades for Jessie.

diff --git a/resources/puppetlabs/lein-ezbake/template/foss/ext/debian/postinst.erb b/resources/puppetlabs/lein-ezbake/template/foss/ext/debian/postinst.erb
--- a/resources/puppetlabs/lein-ezbake/template/foss/ext/debian/postinst.erb
+++ b/resources/puppetlabs/lein-ezbake/template/foss/ext/debian/postinst.erb
@@ -4,12 +4,16 @@
 
 # On upgrade, we should restart the service if it's running
 if [ $1 = 'configure' -a -n $2 ] ; then
-  if [ -x '/etc/init.d/<%= EZBake::Config[:project] %>' ] ; then
+  if [ -e "/lib/systemd/system/<%= EZBake::Config[:project] -%>.service" ] ; then
+    # Using systemd
+    if [ -e '/etc/init.d/<%= EZBake::Config[:project] %>' ] ; then
+      # We need to clean up the old sysv files if they still exist
+      rm '/etc/init.d/<%= EZBake::Config[:project] %>'
+    fi
+    systemctl daemon-reload >/dev/null 2>&1 || :
+    systemctl try-restart <%= EZBake::Config[:project] %>.service ||:
+  else
     # Using sysv
     invoke-rc.d <%= EZBake::Config[:project] %> try-restart || :
-  elif [ -x /bin/systemctl ] ; then
-    # Using systemd
-    systemctl daemon-reload >/dev/null 2>&1 || :
-    systemctl try-restart <%= EZBake::Config[:project] %>.service
   fi
 fi
