(PE-3516) Add status functions, implement condrestart
Having conditional restart available makes a lot of the spec file post
and pre logic cleaner. Instead of stopping the service, laying down a
file, and then starting it afterward, we can just only restart the
service if it is running, which will accomplish the same thing. This
commit adds functions for status and restart where needed and implements
the condition restart behavior described above.

diff --git a/template/foss/ext/debian/ezbake.init.erb b/template/foss/ext/debian/ezbake.init.erb
--- a/template/foss/ext/debian/ezbake.init.erb
+++ b/template/foss/ext/debian/ezbake.init.erb
@@ -73,6 +73,45 @@ do_stop()
     return "$RETVAL"
 }
 
+#
+# Function that gets the status of the daemon/service
+#
+get_status()
+{
+    status_of_proc -p $PIDFILE "$JAVA_BIN" "$NAME"
+    return $?
+}
+
+#
+# Function that gets the status of the daemon/service
+# and makes no output
+#
+get_status_q()
+{
+    get_status >/dev/null 2>&1
+}
+
+
+#
+# Function that restarts the daemon/service
+#
+do_restart()
+{
+    do_stop
+    case "$?" in
+      0|1)
+        do_start
+        case "$?" in
+            0) log_end_msg 0 ;;
+            1) log_end_msg 1 ;; # Old process is still running
+            *) log_end_msg 1 ;; # Failed to start
+        esac
+        ;;
+      *)
+        # Failed to stop
+        log_end_msg 1
+        ;;
+    esac
 }
 
 case "$1" in
@@ -93,32 +132,23 @@ case "$1" in
     esac
     ;;
   status)
-       status_of_proc -p $PIDFILE "$JAVA_BIN" "$NAME" && exit 0 || exit $?
-       ;;
+    get_status
+    exit $?
+    ;;
+  condrestart|try-restart)
+    get_status_q || exit 0
+    do_restart
+    ;;
   restart|force-reload)
     #
     # If the "reload" option is implemented then remove the
     # 'force-reload' alias
     #
-    log_daemon_msg "Restarting $DESC" "$NAME"
-    do_stop
-    case "$?" in
-      0|1)
-        do_start
-        case "$?" in
-            0) log_end_msg 0 ;;
-            1) log_end_msg 1 ;; # Old process is still running
-            *) log_end_msg 1 ;; # Failed to start
-        esac
-        ;;
-      *)
-        # Failed to stop
-        log_end_msg 1
-        ;;
-    esac
+    [ "$VERBOSE" != no ] && log_daemon_msg "Restarting $DESC" "$NAME"
+    do_restart
     ;;
   *)
-    echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+    echo "Usage: $SCRIPTNAME {start|stop|status|condrestart|try-restart|restart|force-reload}" >&2
     exit 3
     ;;
 esac
