(maint) Whitespace cleanup in init script templates (2 space => 4 space tabs)

diff --git a/template/foss/ext/debian/ezbake.init.erb b/template/foss/ext/debian/ezbake.init.erb
--- a/template/foss/ext/debian/ezbake.init.erb
+++ b/template/foss/ext/debian/ezbake.init.erb
@@ -15,9 +15,9 @@
 # You should only need to edit the default/<%= EZBake::Config[:project] %> file and not
 #   this init script directly
 if [ -r "/etc/default/<%= EZBake::Config[:project] %>" ] ; then
-  . /etc/default/<%= EZBake::Config[:project] %>
+    . /etc/default/<%= EZBake::Config[:project] %>
 else
-  exit 1
+    exit 1
 fi
 
 # PATH should only include /usr/* if it runs after the mountnfs.sh script
@@ -99,58 +99,58 @@ do_restart()
 {
     do_stop
     case "$?" in
-      0|1)
-        do_start
-        case "$?" in
-            0) log_end_msg 0 ;;
-            1) log_end_msg 1 ;; # Old process is still running
-            *) log_end_msg 1 ;; # Failed to start
-        esac
-        ;;
-      *)
-        # Failed to stop
-        log_end_msg 1
-        ;;
+        0|1)
+            do_start
+            case "$?" in
+                0) log_end_msg 0 ;;
+                1) log_end_msg 1 ;; # Old process is still running
+                *) log_end_msg 1 ;; # Failed to start
+            esac
+            ;;
+        *)
+            # Failed to stop
+            log_end_msg 1
+            ;;
     esac
 }
 
 case "$1" in
-  start)
-    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
-    do_start
-    case "$?" in
-        0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-        2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-    esac
-    ;;
-  stop)
-    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
-    do_stop
-    case "$?" in
-        0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-        2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-    esac
-    ;;
-  status)
-    get_status
-    exit $?
-    ;;
-  condrestart|try-restart)
-    get_status_q || exit 0
-    do_restart
-    ;;
-  restart|force-reload)
-    #
-    # If the "reload" option is implemented then remove the
-    # 'force-reload' alias
-    #
-    [ "$VERBOSE" != no ] && log_daemon_msg "Restarting $DESC" "$NAME"
-    do_restart
-    ;;
-  *)
-    echo "Usage: $SCRIPTNAME {start|stop|status|condrestart|try-restart|restart|force-reload}" >&2
-    exit 3
-    ;;
+    start)
+        [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+        do_start
+        case "$?" in
+            0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+            2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+        esac
+        ;;
+    stop)
+        [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+        do_stop
+        case "$?" in
+            0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+            2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+        esac
+        ;;
+    status)
+        get_status
+        exit $?
+        ;;
+    condrestart|try-restart)
+        get_status_q || exit 0
+        do_restart
+        ;;
+    restart|force-reload)
+        #
+        # If the "reload" option is implemented then remove the
+        # 'force-reload' alias
+        #
+        [ "$VERBOSE" != no ] && log_daemon_msg "Restarting $DESC" "$NAME"
+        do_restart
+        ;;
+    *)
+        echo "Usage: $SCRIPTNAME {start|stop|status|condrestart|try-restart|restart|force-reload}" >&2
+        exit 3
+        ;;
 esac
 
 :
