(EZ-101) Corrected error message for restart file dir permissions
This commit corrects the content of the error message which is written
when the owner/group on the base directory for a restart file cannot be
changed.

diff --git a/resources/puppetlabs/lein-ezbake/template/global/ext/ezbake-functions.sh.erb b/resources/puppetlabs/lein-ezbake/template/global/ext/ezbake-functions.sh.erb
--- a/resources/puppetlabs/lein-ezbake/template/global/ext/ezbake-functions.sh.erb
+++ b/resources/puppetlabs/lein-ezbake/template/global/ext/ezbake-functions.sh.erb
@@ -128,7 +128,7 @@ init_restart_file()
             fi
             chown $user:$group "$restart_file_base_dir"
             if [ $? -ne 0 ]; then
-                echo "Unable to create set permissions for restart file at ${restart_file_base_dir}" 1>&2
+                echo "Unable to set permissions for base directory of restart file at ${restart_file_base_dir}" 1>&2
                 return 1
             fi
         fi
