(EZ-101) Move restart file initialization into common helper
This commit moves the logic which initializes the restart file into a
common helper function, init_restart_file, which is called from both the
start and reload scripts.

diff --git a/resources/puppetlabs/lein-ezbake/template/global/ext/ezbake-functions.sh.erb b/resources/puppetlabs/lein-ezbake/template/global/ext/ezbake-functions.sh.erb
--- a/resources/puppetlabs/lein-ezbake/template/global/ext/ezbake-functions.sh.erb
+++ b/resources/puppetlabs/lein-ezbake/template/global/ext/ezbake-functions.sh.erb
@@ -112,6 +112,44 @@ kill_pid()
     return 0
 }
 
+init_restart_file()
+{
+    local restart_file="${1:?}"
+    local restart_file_base_dir="$(dirname "$restartfile")"
+    local user="${USER:-<%= EZBake::Config[:user] %>}"
+    local group="${GROUP:-<%= EZBake::Config[:group] %>}"
+
+    if [ ! -e "$restartfile" ]; then
+        if [ ! -d "$restart_file_base_dir" ]; then
+            mkdir -p "$restart_file_base_dir"
+            if [ $? -ne 0 ]; then
+                echo "Unable to create base directory for restart file at ${restart_file_base_dir}" 1>&2
+                return 1
+            fi
+            chown $user:$group "$restart_file_base_dir"
+            if [ $? -ne 0 ]; then
+                echo "Unable to create set permissions for restart file at ${restart_file_base_dir}" 1>&2
+                return 1
+            fi
+        fi
+        echo -n "0" > "$restart_file"
+        if [ $? -ne 0 ]; then
+            echo "Unable to create restart file at ${restart_file}" 1>&2
+            return 1
+        fi
+        chown $user:$group "$restart_file"
+        if [ $? -ne 0 ]; then
+            echo "Unable to set permissions for restart file at ${restart_file}" 1>&2
+            return 1
+        fi
+    elif [ ! -r "$restart_file" ] || [ ! -w "$restart_file" ]; then
+        echo "The restart-file at ${restart_file} is not readable and/or writeable." 1>&2
+        return 1
+    fi
+
+    return 0
+}
+
 if [ "$0" = "$BASH_SOURCE" ] ;then
     COMMAND=${1:?}
     export $(systemctl show -p MainPID <%= EZBake::Config[:project] %>.service)
