(EZ-101) Specify restart file option via TK command line
This commit adds "restart-file" to the Java command lines in the start
and foreground scripts.

diff --git a/resources/puppetlabs/lein-ezbake/template/global/ext/cli/foreground.erb b/resources/puppetlabs/lein-ezbake/template/global/ext/cli/foreground.erb
--- a/resources/puppetlabs/lein-ezbake/template/global/ext/cli/foreground.erb
+++ b/resources/puppetlabs/lein-ezbake/template/global/ext/cli/foreground.erb
@@ -1,5 +1,16 @@
 #!/usr/bin/env bash
 
+restartfile="/opt/puppetlabs/server/data/<%= EZBake::Config[:real_name] %>/restartcounter"
+
+if [ ! -e "${INSTALL_DIR}/ezbake-functions.sh" ]; then
+    echo "Unable to find ${INSTALL_DIR}/ezbake-functions.sh script, failing start." 1>&2
+    exit 1
+fi
+
+. "${INSTALL_DIR}/ezbake-functions.sh"
+
+init_restart_file "$restartfile" || exit $?
+
 if !(echo "${@}" | grep -e "--debug" -q)
 then
     LOG_APPENDER="-Dlogappender=STDOUT"
@@ -9,6 +20,7 @@ COMMAND="${JAVA_BIN} ${JAVA_ARGS} ${LOG_APPENDER} \
          -cp ${INSTALL_DIR}/<%= EZBake::Config[:uberjar_name] %> \
          clojure.main -m <%= EZBake::Config[:main_namespace] %> \
          --config ${CONFIG} --bootstrap-config ${BOOTSTRAP_CONFIG} \
+         --restart-file "${restartfile}" \
          ${@}"
 
 pushd "${INSTALL_DIR}" &> /dev/null
