(SERVER-508) Run puppetserver foreground directly when correct user
Without this patch the puppetserver foreground command runs the
puppetserver command through `su` when the parent context is running as
non-root.  This is a problem because it's not necessary to switch users
in all cases.  If we're already the correct user we can run the command
directly, and if we're not the correct user running through `su` is
likely the wrong thing to do because this will prompt for a password
when non-root and the correct user to run as likely has no password set.

This address Jeremy's comment to that effect at [1].

[1]: https://github.com/puppetlabs/ezbake/pull/212#issuecomment-85141407

diff --git a/resources/puppetlabs/lein-ezbake/template/global/ext/cli/foreground.erb b/resources/puppetlabs/lein-ezbake/template/global/ext/cli/foreground.erb
--- a/resources/puppetlabs/lein-ezbake/template/global/ext/cli/foreground.erb
+++ b/resources/puppetlabs/lein-ezbake/template/global/ext/cli/foreground.erb
@@ -12,11 +12,23 @@ COMMAND="${JAVA_BIN} ${JAVA_ARGS} ${LOG_APPENDER} \
          ${@}"
 
 pushd "${INSTALL_DIR}" &> /dev/null
-if [ "$EUID" = "0" ] && command -v runuser &> /dev/null; then
-  runuser "${USER}" -s /bin/bash -c "$COMMAND"
-elif command -v su &> /dev/null; then
-  su "${USER}" -s /bin/bash -c "$COMMAND"
+
+# USER is bound to the user puppetserver should run as in default or cli-app.
+# USER in this context is not following Unix convention of being set to LOGNAME
+if [ "$LOGNAME" = "$USER" ]; then
+  $COMMAND
+elif [ "$EUID" = "0" ]; then
+  if command -v runuser &> /dev/null; then
+    runuser "${USER}" -s /bin/bash -c "$COMMAND"
+  elif command -v su &> /dev/null; then
+    su "${USER}" -s /bin/bash -c "$COMMAND"
+  else
+    sudo -u "${USER}" $COMMAND
+  fi
 else
-  sudo -u "${USER}" $COMMAND
+  echo "ERROR: This shell is not running as root or $USER" >&2
+  echo "Cannot switch over to $USER, please start puppetserver foreground" >&2
+  echo "from a root or $USER shell." >&2
+  exit 1
 fi
 popd &> /dev/null
