(EZ-97) Echo error message when process exits during reload or HUP fails
This commit adds an echo statement if a process exits during a reload
attempt or a HUP signal cannot be sent to the process.  The commit also
replaces 'set -e' with 'set +e' to allow for the exit code for a 'kill
-0 <pid>' to be inspected rather than having the script just exit for a
non-zero value.

diff --git a/resources/puppetlabs/lein-ezbake/template/global/ext/cli/reload.erb b/resources/puppetlabs/lein-ezbake/template/global/ext/cli/reload.erb
--- a/resources/puppetlabs/lein-ezbake/template/global/ext/cli/reload.erb
+++ b/resources/puppetlabs/lein-ezbake/template/global/ext/cli/reload.erb
@@ -1,16 +1,24 @@
 #!/usr/bin/env bash
-set -e
+set +e
 
 restartfile=<%= EZBake::Config[:restart_file] %>
 timeout=<%= EZBake::Config[:start_timeout] %>
 
 if [ -r "$restartfile" ];  then
     pid=$(pgrep -f <%= EZBake::Config[:uberjar_name] %>)
-    kill -HUP $pid
+    kill -HUP $pid >/dev/null 2>&1
+    if [ $? -ne 0 ]; then
+        echo "Service not running so cannot be reloaded" 1>&2
+        exit 1
+    fi
     cur=$(head -n 1 "$restartfile")
     initial=$cur
     while [ "$cur" == "$initial" ] ;do
         kill -0 $pid >/dev/null 2>&1
+        if [ $? -ne 0 ]; then
+            echo "Process $pid exited before reload had completed" 1>&2
+            exit 1
+        fi
         sleep 0.1
         cur=$(head -n 1 "$restartfile")
 
