(EZ-99) Add start/stop error message if ezbake-functions.sh not found
This commit adds an error message and explicit exit return to the start and
stop scripts if the ezbake-functions.sh script cannot be found.

diff --git a/resources/puppetlabs/lein-ezbake/template/global/ext/cli/start.erb b/resources/puppetlabs/lein-ezbake/template/global/ext/cli/start.erb
--- a/resources/puppetlabs/lein-ezbake/template/global/ext/cli/start.erb
+++ b/resources/puppetlabs/lein-ezbake/template/global/ext/cli/start.erb
@@ -9,7 +9,12 @@ dir=$(dirname "$restartfile")
 realname="<%= EZBake::Config[:real_name] %>"
 PIDFILE="/var/run/puppetlabs/${realname}/${realname}.pid"
 
-[ -e "${INSTALL_DIR}/ezbake-functions.sh" ] && . "${INSTALL_DIR}/ezbake-functions.sh"
+if [ ! -e "${INSTALL_DIR}/ezbake-functions.sh" ]; then
+    echo "Unable to find ${INSTALL_DIR}/ezbake-functions.sh script, failing start." 1>&2
+    exit 1
+fi
+
+. "${INSTALL_DIR}/ezbake-functions.sh"
 
 write_pid_file() {
     if [ ! -d "/var/run/puppetlabs/${realname}" ]; then
diff --git a/resources/puppetlabs/lein-ezbake/template/global/ext/cli/stop.erb b/resources/puppetlabs/lein-ezbake/template/global/ext/cli/stop.erb
--- a/resources/puppetlabs/lein-ezbake/template/global/ext/cli/stop.erb
+++ b/resources/puppetlabs/lein-ezbake/template/global/ext/cli/stop.erb
@@ -5,7 +5,12 @@ pid=$(pgrep -f <%= EZBake::Config[:uberjar_name] %>)
 realname="<%= EZBake::Config[:real_name] %>"
 PIDFILE="/var/run/puppetlabs/${realname}/${realname}.pid"
 
-[ -e "${INSTALL_DIR}/ezbake-functions.sh" ] && . "${INSTALL_DIR}/ezbake-functions.sh"
+if [ ! -e "${INSTALL_DIR}/ezbake-functions.sh" ]; then
+    echo "Unable to find ${INSTALL_DIR}/ezbake-functions.sh script, failing stop." 1>&2
+    exit 1
+fi
+
+. "${INSTALL_DIR}/ezbake-functions.sh"
 
 if [ -z $pid ]; then
     rm -f "$PIDFILE"
