bindir fixes, add 'exit' statement for cli-env wrapper

diff --git a/staging-templates/cli-env.erb b/staging-templates/cli-env.erb
--- a/staging-templates/cli-env.erb
+++ b/staging-templates/cli-env.erb
@@ -5,5 +5,6 @@ if [ -r "/etc/default/<%= EZBake::Config[:real_name] -%>" ] ; then
 elif [ -r  "/etc/sysconfig/<%= EZBake::Config[:real_name] -%>" ] ; then
     . /etc/sysconfig/<%= EZBake::Config[:real_name] %>
 else
-    TODO: DIE!!!
+    echo "You seem to be missing some important configuration files; could not find /etc/default/<%= EZBake::Config[:real_name] -%> or /etc/sysconfig/<%= EZBake::Config[:real_name] -%>" >&2
+    exit 1
 fi
